//在chunkbase复制传送指令之后触发次脚本进行tp。坐标不对或者过大可能导致游戏崩溃( 没有进行限制 )

const clip = Utils.getClipboard().split(' ')
const player = Player.getPlayer()
const pos = player.getPos()
Chat.log(clip[1])
Chat.log(clip[3])
player.setPos(pos.x, 512, pos.z)
let x = parseInt(clip[1])
let z = parseInt(clip[3])
Chat.log([x,z]) 
Client.waitTick(2)
player.setPos(x+0.5, 512.0, z+0.5)
player.setPos(x+0.5, 70.0, z+0.5)
Player.getPlayer().setVelocity(0.0,0.1,0.0)